Retrieves a list of all products of a category
---
tags:
  - Products
parameters:
  - name: category_id
    in: path
    type: integer
    required: true
    description: unique id of a category

responses:
  200:
    description: request executed successful
    schema:
      type: array
      items:
        properties:
          id:
            type: integer
            description: product id
          name:
            type: string
            description: product name
          url_image:
            type: string
            description: image url
          price:
            type: number
            description: product price
          discount:
            type: integer
            description: product discount
          category:
            type: integer
            description: product's category id
  404:
    description: Category not found
